### ISSUE TITLE
用的是vscode的哪个版本，提示不兼容

### ISSUE THREAD

**Issue by chenpengjun** [giscafer/leek-fund#1]

**Comment by giscafer** [comment]
`v1.47.0` 的版本，插件开发的时候随便写的，自己用的是 `v1.47.3`。

可以升级一下。下次发布我降级兼容到 v1.40 左右吧。

**Comment by giscafer** [comment]
@chenpengjun 插件升级了，兼容到了 `v.1.29.0` 版本
