### ISSUE TITLE
配置股票代码后无法显示

### ISSUE THREAD

**Issue by dadatom** [giscafer/leek-fund#10]
![image](https://user-images.githubusercontent.com/33886943/89604486-f29c0e00-d89d-11ea-8cbe-40266f5de8ae.png)

**Comment by giscafer** [comment]
@dadatom 版本信息发一下。按理不会的，错误的话也会显示股票错误。

另外，为了便于排查问题，建议把你的配置json文件发一下。

eg: 

```json
 "leek-fund.stocks": [
  
    "0000001",
    "0000300",
    "0000016",
    "0000688",
    "0399006",
    "0000913",
    "0000905",
    "0600519",
    "0399975",
    "0399995",
    "hk09988"
  ]
```

**Comment by giscafer** [comment]
#5 

`v1.0.0` 版本已经修复问题

**Comment by MyYaYa** [comment]
有同样的问题
![image](https://user-images.githubusercontent.com/6195920/150352869-59c4eeb4-4878-4471-9430-8e6924220f8c.png)
