### ISSUE TITLE
请求添加量比指标

### ISSUE THREAD

**Issue by q1048009461** [giscafer/leek-fund#101]
请描述下这个功能的作用：
1、使用场景：买股指标，通过量比观察该股当日热度。

请描述一下你期望这个新功能的 API 是如何使用的，并提供一些代码示例。
1：可以放置到行情展示。或者多添加一些指标，例如量比，换手率，3日涨幅，5分钟涨速等，可以不全部默认展示，而是让用户自行选择是否展示指标，并可以通过量比，涨速等进行排序。

**Comment by iporer** [comment]
这是行情查看插件，不是选股软件，插件不记录股票的具体数据，能显示的指标都是抓的网页数据。
更多需求可以考虑去东方财富网或者同花顺网站查看。

**Comment by giscafer** [comment]
不考虑此 feature
