### ISSUE TITLE
数据刷新报错，很频繁

### ISSUE THREAD

**Issue by xspeed1989** [giscafer/leek-fund#103]
@giscafer 
fail: Stock error https://hq.sinajs.cn/list=sz002475,sz300251,sh603501,sz002624,sh000001,sh000300,sh000016,sh000688,hk03690,hk00700,usr_ixic,usr_dji,usr_inx,sh600196,sz300180

没有开代理或者其他，浏览器打开正常

![image](https://user-images.githubusercontent.com/5162926/99341180-5f26a000-28c4-11eb-88bd-b039fd54f348.png)

![image](https://user-images.githubusercontent.com/5162926/99341203-6cdc2580-28c4-11eb-9e5d-e7e85bce54c2.png)

**Comment by giscafer** [comment]
设置设置时间，按理是10秒轮询一次。没开VPN吗？

**Comment by xspeed1989** [comment]
> 设置设置时间，按理是10秒轮询一次。没开VPN吗？
@giscafer 
没开VPN， 就是10S一次，但是还是频繁报错

**Comment by giscafer** [comment]
@xspeed1989 这个无法重现，群里问问大家看看

**Comment by xspeed1989** [comment]
> @xspeed1989 这个无法重现，群里问问大家看看

@giscafer 电报群好像没人说话，有没有微信群哇

**Comment by giscafer** [comment]
https://github.com/giscafer/leek-fund/commit/173d2e3a5680ecd9c9cd87b67d20f18cf148dd08

网络问题无法帮忙找问题，自己多看看。频繁提示的情况控制只弹窗一次，当然是针对插件初始化后。重启后会重置

**Comment by xspeed1989** [comment]
> v1.7.2 版本生效：[173d2e3](https://github.com/giscafer/leek-fund/commit/173d2e3a5680ecd9c9cd87b67d20f18cf148dd08)
> 
> 网络问题无法帮忙找问题，自己多看看。频繁提示的情况控制只弹窗一次，当然是针对插件初始化后。重启后会重置

@giscafer 貌似是DNS解析失败出现的问题，现在我把hq.sinajs.cn这个域名加到了HOST不知道有不有效
