### ISSUE TITLE
美股盘前盘后数据支持

### ISSUE THREAD

**Issue by ringcrl** [giscafer/leek-fund#114]
## Other reference [Optional]

1、这个功能的使用场景是什么？

支持美股状态栏显示盘前盘后数据，方便未开盘时间查看

2、这个功能解决你的什么问题？

在盘前了解股票情况

**Comment by giscafer** [comment]
盘前盘后就不考虑支持了吧。功能太多就复杂起来，专业的情况下还是看专业软件和网页吧。
