### ISSUE TITLE
有的基金代码不能识别，不知道是配置的不对，还是接口不兼容。

### ISSUE THREAD

**Issue by ren2881971** [giscafer/leek-fund#13]
比如 000835  华润元大富时中国A50 指数基金

**Comment by giscafer** [comment]
http://fundgz.1234567.com.cn/js/000835.js?callback=a 

可以啊

![image](https://user-images.githubusercontent.com/8676711/89702485-4e38cb00-d974-11ea-9301-e38f9c730acb.png)

手动配置错了吧，可以用这里添加
![image](https://user-images.githubusercontent.com/8676711/89702495-66a8e580-d974-11ea-87e5-9f2c8872c2cf.png)

**Comment by Tback1** [comment]
货币基金003474 000198 能获取数据，但是获取不到名称
![image](https://user-images.githubusercontent.com/8872546/89704926-50f2ea80-d98b-11ea-8126-0a70939b9926.png)

**Comment by giscafer** [comment]
@Tback1 爬虫接口不支持那就没法子，目前没找到好的接口。知道可以告知一下
```
// 接口无法获取到数据
http://fundgz.1234567.com.cn/js/003474.js?callback=a
```

**Comment by deepsea887** [comment]
看到默认的基金列表，有一半是我买过的（哈哈哈）

**Comment by giscafer** [comment]
`v1.5.0` 支持
