### ISSUE TITLE
货币基金无法获取到名称

### ISSUE THREAD

**Issue by Tback1** [giscafer/leek-fund#14]
货币基金003474 000198 能获取数据，但是获取不到名称
![image](https://user-images.githubusercontent.com/8872546/89704941-797ae480-d98b-11ea-800c-16f321997e4c.png)

![image](https://user-images.githubusercontent.com/8872546/89704926-50f2ea80-d98b-11ea-8126-0a70939b9926.png)

**Comment by giscafer** [comment]
接口不支持，无法获取，只几个基金是场内还是场外？

**Comment by Tback1** [comment]
这两支都是场内，南方系和大名鼎鼎的余额宝后的天弘。

**Comment by giscafer** [comment]
@Tback1 好的，目前没有看到特别好的基金接口。持续看吧。插件升级过了，功能新增了不少，可以更新试试。

**Comment by giscafer** [comment]
@Tback1 是这个货币基金吗？相当于股票了吧

http://suggest3.sinajs.cn/suggest/type=2&key=000198


这个在这个接口没找到详细信息

```
https://hq.sinajs.cn/list=of000198
```

**Comment by Tback1** [comment]
> @Tback1 是这个货币基金吗？相当于股票了吧
> 
> http://suggest3.sinajs.cn/suggest/type=2&key=000198
> 
> 这个在这个接口没找到详细信息
> 
> ```
> https://hq.sinajs.cn/list=of000198
> ```

是的，就是这只

**Comment by Tback1** [comment]
走势图，每日收益其他都是正常的，就是没名称~要不下一版本添加一个自定义名称的功能，自己本地定义一下这些无法获取的就行了

**Comment by giscafer** [comment]
> 走势图，每日收益其他都是正常的，就是没名称~要不下一版本添加一个自定义名称的功能，自己本地定义一下这些无法获取的就行了

这个是走股票的接口的吧，是股票基金吧？？

**Comment by Tback1** [comment]
> > 走势图，每日收益其他都是正常的，就是没名称~要不下一版本添加一个自定义名称的功能，自己本地定义一下这些无法获取的就行了
> 
> 这个是走股票的接口的吧，是股票基金吧？？

这个不知道新浪怎么划分的，按理说这两个都是投资短期债券为主，不是股票基金

**Comment by giscafer** [comment]
是不是类似这个的 #60 ，基金有些是接口不支持的

**Comment by Tback1** [comment]
> 是不是类似这个的 #60 ，基金有些是接口不支持的

我看了，不会啊，这是国内基金，不会调用海外的T2接口吧

**Comment by giscafer** [comment]
`v1.5.0` 支持海外基展示（无实时信息）
