### ISSUE TITLE
我的版本是1.47，还是用不了，，，，，

### ISSUE THREAD

**Issue by maguangxian** [giscafer/leek-fund#15]
# ***RT***

**Comment by giscafer** [comment]
有截图吗？最新版目前是 `v1.1.1`，卸载后按照，然后重启 `VSCode`  试试

**Comment by giscafer** [comment]
请问系统是 Linux吗。最新版本 `v1.1.5` 已修复问题，可以试试

**Comment by giscafer** [comment]
还有个不能使用的可能原因：电脑开启了代理，使得插件https请求接口走了系统代理，接口无法正常访问，数据出不来。建议关闭代理等再试试。

无响应本 issue 关闭先了。
