### ISSUE TITLE
更新版本后界面变空白了

### ISSUE THREAD

**Issue by liuzhenwubigboss** [giscafer/leek-fund#17]
![image](https://user-images.githubusercontent.com/31624973/89750095-19a44b00-dafd-11ea-88bf-cf22e72e9a02.png)
最新版本1.1.4

**Comment by giscafer** [comment]
好奇怪，我用虚拟机 新安装 VSCode，然后安装插件都没问题。
![image](https://user-images.githubusercontent.com/8676711/89752271-4c9f0c80-db06-11ea-9f5f-f58617bdd076.png)

你是从什么版本升级到 1.1.4? 卸载重新安装试试？

**Comment by liuzhenwubigboss** [comment]
之前是1.1.2，卸载了几次重新安装也不行。是不是配置文件有问题？
![image](https://user-images.githubusercontent.com/31624973/89753776-211f2080-db0c-11ea-9a6b-fca05ed1f459.png)

**Comment by giscafer** [comment]
[leek-fund-1.1.4.vsix.zip](https://github.com/giscafer/leek-fund/files/5049230/leek-fund-1.1.4.vsix.zip) 下载解压这个附件，手动安装试试可不可以。打包方式变了一下，看能不能解决你的问题。解决了线上的打包也换成一样的。（先卸载当前的插件）

![image](https://user-images.githubusercontent.com/8676711/89755053-a73d6600-db10-11ea-9ef7-cdb06baf0c0f.png)

**Comment by liuzhenwubigboss** [comment]
![image](https://user-images.githubusercontent.com/31624973/89755838-5bd88700-db13-11ea-8d0e-687f48bfab35.png)
还是不行，我试试回滚之前版本

**Comment by giscafer** [comment]
@liuzhenwubigboss 滚回`1.1.2 `、`1.1.0`、`0.2.1` 分别试试？或者升级 VSCode到 `1.47+` 最新？

**Comment by liuzhenwubigboss** [comment]
回滚到0.2.1解决了 :joy:

**Comment by giscafer** [comment]
@liuzhenwubigboss #19 加群有空找你重现问题才行呀。

**Comment by liuzhenwubigboss** [comment]
> @liuzhenwubigboss #19 加群有空找你重现问题才行呀。

已加
