### ISSUE TITLE
两点小期待

### ISSUE THREAD

**Issue by strangersss** [giscafer/leek-fund#18]
- 希望可以加入基金的走势图

- 基金股票如果可以再进行自定义分组就好了

**Comment by giscafer** [comment]
基金走势图容易实现，现在难点是还没找到接口支撑，没数据。

分组的话最后再看吧。有人PR当然很好~

**Comment by strangersss** [comment]
https://image.sinajs.cn/newchart/v5/fund/nav/ss/150206.gif 可以看下这个，改一下基金代码就可以了，尝试了几个没有问题

**Comment by giscafer** [comment]
> https://image.sinajs.cn/newchart/v5/fund/nav/ss/150206.gif 可以看下这个，改一下基金代码就可以了，尝试了几个没有问题

感谢提供

**Comment by giscafer** [comment]
@strangersss 有实时基金走势图吗？你给的这个是历史走势图

**Comment by giscafer** [comment]
`v1.1.6` 版本已支撑历史基金走势图 查看

![image](https://user-images.githubusercontent.com/8676711/89792899-c01d3a00-db57-11ea-95fd-6c24a71a8696.png)

**Comment by giscafer** [comment]
第二个建议加入了 Projects 计划，将来可能支持。此 issue 关闭先
