### ISSUE TITLE
美股代码支持，代码prefix是usr_

### ISSUE THREAD

**Issue by tiny656** [giscafer/leek-fund#24]
版本 `v1.0.0` 已支持

```
  // 配置需要监控的股票代码（新浪接口，所以去新浪找股票代码比较合适）
  // 深股股，上证指数：sh000001
  // 港股股票代码，如阿里巴巴：hk09988，腾讯：hk00700，美团：hk03690
  // 美股指数代码，如道琼斯指数: gb_dji，纳斯达克: gb_ixic，标普500: gb_inx
  // 如配置后没有数据，可以用这个链接测试一下是否有返回数据：https://hq.sinajs.cn/list=hk00700

  "leek-fund.stocks": [
    "sh000001",
    "sh000300",
    "sh000016",
    "sh000688",
    "sh000913",
    "sh000905",
    "hk03690",
    "hk00700",
    "hk09988",
    "gb_ixic",
    "gb_dji",
    "gb_inx"
  ],
```

_Originally posted by @giscafer in https://github.com/giscafer/leek-fund/issues/9#issuecomment-670819343_

数据接口
美股:http://hq.sinajs.cn/list=usr_pdd
美股可以用这个接口的，usr_，代码里hardcode还不支持这个
走势图
美股sample:https://image.sinajs.cn/newchart/usstock/min/pdd.gif
港股sample:https://image.sinajs.cn/newchart/hk_stock/min/09988.gif

**Comment by giscafer** [comment]
@SubinY Have a try?

**Comment by SubinY** [comment]
> @SubinY Have a try?

go go go, fininsh this feature on tomorrow

**Comment by SubinY** [comment]
[美股代码支持 #37 ](https://github.com/giscafer/leek-fund/pull/37)
