### ISSUE TITLE
不同地区股票数据自动更新策略

### ISSUE THREAD

**Issue by httpcheck** [giscafer/leek-fund#26]
股票：
A股：9:30--15:00
港股：9:30--16:00
美股：21:30--4:00（夏令时）、22:30--5:00（冬令时） 取并集 21:30--5:00
其他：暂时与美股时间相同

基金：
由于美股/港股基金相对A股基金较少，暂时采用A股9:30--15:00策略

todo by @httpcheck

**Comment by tyePhDCandy** [comment]
建议在文档中添加以下内容，方便查询各个市场的auto refresh time interval.
```

股票：
A股：9:30--15:00
港股：9:30--16:00
美股：21:30--4:00（夏令时）、22:30--5:00（冬令时） 取并集 21:30--5:00
其他：暂时与美股时间相同

基金：
由于美股/港股基金相对A股基金较少，暂时采用A股9:30--15:00策略
```

**Comment by giscafer** [comment]
@tyePhDCandy 股票这里未实现，暂不加

**Comment by iporer** [comment]
#84 可以close了
