### ISSUE TITLE
基金的净值估算不会更新

### ISSUE THREAD

**Issue by EverChisato** [giscafer/leek-fund#27]
看到介绍说有自动刷新，但是发现基金的净值估算趋势并不会自动更新，除非重新点击进去，点击左边面板的刷新也是显示更新基金数据，但右边的面板基金趋势图也是没有刷新到

![微信图片_20200812101553](https://user-images.githubusercontent.com/25126812/89967877-14720800-dc85-11ea-8c56-8c6d0184edc8.png)

**Comment by giscafer** [comment]
是的，这里的图片没有做自动更新。

**Comment by giscafer** [comment]
详情页的走势图 20秒刷新一次。（因为图片更新也不是很频繁，所以设置20s），下个版本体现。 `v1.1.9`
