### ISSUE TITLE
底部的 Bar 上的一些文本可能可以针对主题的颜色变换一下 color

### ISSUE THREAD

**Issue by yiliang114** [giscafer/leek-fund#28]
![image](https://user-images.githubusercontent.com/11473889/89968845-86e3e780-dc87-11ea-966d-dca557da9bc5.png)

**Comment by giscafer** [comment]
@yiliang114 这个配置文件可以自己设置。代码判断自动换可能会改掉用户设置的颜色。除非是第一次初始化做的事情，但是只有初始化的时候做就意义不大了。解决方法是可以设置一个色去适应各种背景即可，然后用户自己配置喜欢的颜色。

（目前跌是黑色，改成绿色就差不多了。）

**Comment by yiliang114** [comment]
好像是的~
