### ISSUE TITLE
V2.0的版本迭代需求表中的<基金和股票支持置顶>功能

### ISSUE THREAD

**Issue by ihwf** [giscafer/leek-fund#36]
建议将V2.0的版本迭代需求表中的<基金和股票支持置顶>功能改为自定义排序体验会更好

**Comment by giscafer** [comment]
自定义排序现在是可以通过配置手动调的。后续增强是可以拖拽排序的，类似置顶了。不会只单纯做置顶无自定义排序

**Comment by giscafer** [comment]
已支持置顶功能，大体满足。
