### ISSUE TITLE
ETF需要小数点后三位

### ISSUE THREAD

**Issue by git478345960** [giscafer/leek-fund#40]
现在只能看到小数点后两位，从而导致百分比的计算也有问题

**Comment by giscafer** [comment]
截个图

**Comment by iporer** [comment]
![image](https://user-images.githubusercontent.com/8085344/91941469-db7cfe80-ed2b-11ea-9fdf-8af22b323eb7.png)
![image](https://user-images.githubusercontent.com/8085344/91941496-e6379380-ed2b-11ea-9a87-990439f5c05a.png)
https://hq.sinajs.cn/list=sh512010
@giscafer 
这是场内etf的内容，应该显示三位小数。类似还有场内lof。

另外一个问题是通过UI在股票里面添加不了场内ETF和场内LOF，在基金里面添加ETF和LOF是估值，不是实时交易数值。只能在配置文件里添加
