### ISSUE TITLE
基金FUND收起情况下，会导致STOCK股票栏也停止刷新数据

### ISSUE THREAD

**Issue by wekerSnail** [giscafer/leek-fund#41]
插件版本：1.2.5
vscode:1.48.0

基金栏折叠会导致股票栏数据停止更新

**Comment by giscafer** [comment]
fixed at version  `1.2.6`

**Comment by ihwf** [comment]
这个问题还是存在啊

**Comment by giscafer** [comment]
> 这个问题还是存在啊 @giscafer

正常的，如有问题，建议录屏gif 提 issues

最新版本是 `v1.4.1`
