### ISSUE TITLE
获取股票失败错误

### ISSUE THREAD

**Issue by bingoIsCoder** [giscafer/leek-fund#43]
fail: Stock error http://hq.sinajs.cn/list=sh000001,sh000300,sh000016,sh000688,sh000913,sh000905,hk03690,hk00700,hk09988,gb_ixic,gb_dji,gb_inx,sh603690,sh000651,sh600132,sh601318

vscode右下部分一直弹窗

**Comment by giscafer** [comment]
![image](https://user-images.githubusercontent.com/8676711/90386910-d24b2b00-e0b7-11ea-825d-1ec3f219bd60.png)

查看正常，请检查个人网络情况，以及是否开启了网络代理等
