### ISSUE TITLE
添加股票失败 例如sz123044

### ISSUE THREAD

**Issue by winlans** [giscafer/leek-fund#46]
这个转债是真实存在的， 但是添加的时候由于搜索不出来， 然后不允许添加， 但是直接在配置文件中添加是可以正常显示的。

**Comment by giscafer** [comment]
> 这个转债是真实存在的， 但是添加的时候由于搜索不出来， 然后不允许添加， 但是直接在配置文件中添加是可以正常显示的。

fixed at version `1.2.9`
