### ISSUE TITLE
港股的数据不对

### ISSUE THREAD

**Issue by dofine** [giscafer/leek-fund#5]
用得代码接口港股的数据还在4月份。
https://api.money.126.net/data/feed/hk03690?callback=a

**Comment by giscafer** [comment]
@dofine 这个需要找一下接口才行（目前还不知道什么好接口可以免费用），知道的话欢迎反馈

**Comment by dofine** [comment]
新浪的貌似可以
http://hq.sinajs.cn/list=rt_hk00700,rt_hk03690

**Comment by giscafer** [comment]
@dofine 已替换为新浪接口，版本 `v1.0.0`
