### ISSUE TITLE
建议加一个自持份额和估算收益的功能

### ISSUE THREAD

**Issue by HenryWong-fe** [giscafer/leek-fund#54]
自行添加基金持有份额,估算当前收益及亏损

**Comment by giscafer** [comment]
实现思路说明：
通过接口获取到每个基金的信息（支持批量）
```js
https://fundmobapi.eastmoney.com/FundMNewApi/FundMNFInfo?pageIndex=1&pageSize=50&plat=Android&appType=ttjj&product=EFund&Version=1&deviceid=ssdfsdfsdf&Fcodes=320007,161726
```

然后做计算展示

基金金额设置已实现 ，计算未实现

**Comment by giscafer** [comment]
`v1.5.0` 版本支持基金收益计算

**Comment by HenryWong-fe** [comment]
🐂，太棒了👏

**Comment by HenryWong-fe** [comment]
其实不需要金额,仅需要输入购买的份额和自身购买份额的成本价,即可得出盈亏成本
购买份额与当前净值即为当前价
购买份额与成本净值即为成本价
当前价与成本价的差值即为浮盈及浮亏

**Comment by giscafer** [comment]
> 其实不需要金额,仅需要输入购买的份额和自身购买份额的成本价,即可得出盈亏成本
> 购买份额与当前净值即为当前价
> 购买份额与成本净值即为成本价
> 当前价与成本价的差值即为浮盈及浮亏

这个懂，这里谈一下我的看法。

成本净值接口目前获取不到，所以程序是不知道的。成本净值如果需要用户输入，份额又要输入，这两者的总体维护成本就高了，所以目前版本是输入金额，份额通过金额计算得到。不考虑成本价和总体的浮动盈亏。

因为目前也没有对接天天基金账户的，蚂蚁财富是支付宝的账号，应该是不能对接的（可能需要企业对接）。所以用户在其他基金平台买卖的操作，韭菜盒子也无法知道的，所以，目前只考虑最简单的方式来实现当日的浮动盈亏的估算就够了。真要靠买入成本和一段时间的总体盈亏，APP其实很丰富也满足。

---

`v.1.50` 周一内测没问题才会发布商城。刚兴趣可以提前使用或者帮忙内测，解压附件手动安装：
[leek-fund-1.5.0.vsix.zip](https://github.com/giscafer/leek-fund/files/5178277/leek-fund-1.5.0.vsix.zip)

（会跑源码自己打包也可）

**Comment by HenryWong-fe** [comment]
我这里理解的输入金额是当前基金价值是吗? 等周一开市后,我这边跟进测试一下

**Comment by giscafer** [comment]
> 我这里理解的输入金额是当前基金价值是吗? 等周一开市后,我这边跟进测试一下

持仓金额，比如你用的是蚂蚁财富，这个基金现在有多少钱就填多少钱。（就已经是成本价*份数的了）
