### ISSUE TITLE
期货支持，比如日经255指数

### ISSUE THREAD

**Issue by guannan-he** [giscafer/leek-fund#57]
例如：
https://hq.sinajs.cn/list=b_NKY
日经225代码应该为b_NKY，但是界面没有添加进来
![image](https://user-images.githubusercontent.com/50306947/90999185-88eb6600-e5f8-11ea-906b-f00647fa23c0.png)

**Comment by giscafer** [comment]
这个目前还不支持的。你是手填的吧？GUI 新增按理是搜索不到，过滤掉了。

解释一下 `str_b_` 是什么意思

**Comment by giscafer** [comment]
你这是期货吧。搜索接口都查不到

```
http://suggest3.sinajs.cn/suggest/type=&key=NKY
```

**Comment by guannan-he** [comment]
> 你这是期货吧。搜索接口都查不到
> 
> ```
> http://suggest3.sinajs.cn/suggest/type=&key=NKY
> ```

你好，是期货，srt_b是我的错误😂，sorry
是手填的，在这里：http://finance.sina.com.cn/money/globalindex/asia.shtml
![image](https://user-images.githubusercontent.com/50306947/91009285-d70d6300-e612-11ea-996f-c0b7d85b3bec.png)
找的，我以为能够支持
gui里找到的是usr_nky，但是https://hq.sinajs.cn/list=usr_nky
找不到

**Comment by giscafer** [comment]
不考虑期货。
