### ISSUE TITLE
可以添加一个基金的持仓的股票变化吗？

### ISSUE THREAD

**Issue by lycor1s** [giscafer/leek-fund#58]
请描述下这个功能的作用：

  1、这个功能的使用场景是什么？
        可以看基金持有股票的涨跌。

类似如下截图：
![image](https://user-images.githubusercontent.com/23312700/91007883-a7109080-e60f-11ea-9272-39a5d59a0f14.png)

**Comment by giscafer** [comment]
东方财富有现成的页面链接效果吗？

**Comment by lycor1s** [comment]
有这样的
http://fundf10.eastmoney.com/ccmx_519674.html
![image](https://user-images.githubusercontent.com/23312700/91039392-10f45e80-e63f-11ea-8f34-1e5c6361a953.png)

**Comment by giscafer** [comment]
会写前端吗，欢迎PR

**Comment by lycor1s** [comment]
> 会写前端吗，欢迎PR

不会😂
