### ISSUE TITLE
可以搜索到基金001691和显示走势趋势图，但是列表显示出错

### ISSUE THREAD

**Issue by hooyao** [giscafer/leek-fund#59]
## Bug Report

对于基金001691可以搜索到，可以显示走势和趋势图，但是列表显示出错
## Current Behavior?
![image](https://user-images.githubusercontent.com/659145/91020459-0a58ed80-e625-11ea-8d13-4b6d4d3bca43.png)

## Expected Behavior?
可以正常显示基金001691

## Steps to reproduce [Optional]
在基金列表中添加新基金，搜索基金001691，添加。基金列表中显示出错。

##  Your Environment [Optional]
Version: 1.48.1 (user setup)
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:12:13.244Z (4 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by giscafer** [comment]
和 #13 雷同，接口不支持的话没法支持。

http://fundgz.1234567.com.cn/js/001691.js?callback=a
