### ISSUE TITLE
港股的价格不对

### ISSUE THREAD

**Issue by onlyforyoumylove** [giscafer/leek-fund#61]
港股的价格不对

**Comment by RichardChen1122** [comment]
发现类似问题，例如下面截图， 实际价格是3.06， k线图中的价格是正确的，但列表中显示的价格与实际不一致，手动刷新也没有用

![image](https://user-images.githubusercontent.com/10596709/91515345-8c922c00-e91b-11ea-836c-84db1b593ce7.png)

**Comment by giscafer** [comment]
@RichardChen1122 列表和图是不同的数据来源，有点差距可能是数据来源更新及时性的问题。实时趋势图是几分钟才刷新一次的。列表是实时的。不能作为对比，只有两者都是实时的才可以对比
