### ISSUE TITLE
状态栏显示文字能否自定义，或默认为白色。

### ISSUE THREAD

**Issue by BrightVan** [giscafer/leek-fund#64]
很简单的一个问题。状态栏背景是蓝色而下跌文字显示绿色就会看不清。下面截图，凑近还勉强看得清，实际上是完全看不清，不会离得那么近。
![image](https://user-images.githubusercontent.com/9381559/91926110-19b4f680-ed09-11ea-82ad-f141beafcc63.png)

**Comment by BrightVan** [comment]
我发现上面这个问题可以忽略了，但建议文档说明，明确下，设置涨跌的颜色就是针对状态栏的，而且，默认跌的颜色改成白色会比较好。

**Comment by brightzoe** [comment]
> 我发现上面这个问题可以忽略了，但建议文档说明，明确下，设置涨跌的颜色就是针对状态栏的，而且，默认跌的颜色改成白色会比较好。

我也才发现，这个颜色竟然是针对状态栏的

**Comment by iporer** [comment]
> 我发现上面这个问题可以忽略了，但建议文档说明，明确下，设置涨跌的颜色就是针对状态栏的，而且，默认跌的颜色改成白色会比较好。

默认跌的颜色置空效果最好，颜色和VSCODE主题颜色一致

**Comment by giscafer** [comment]
支持自定义设置啊。没发现那个功能吗，就叫“:art:设置涨跌颜色”，颜色不满意，还可以打开配置自己手填

**Comment by giscafer** [comment]
> 我发现上面这个问题可以忽略了，但建议文档说明，明确下，设置涨跌的颜色就是针对状态栏的，而且，默认跌的颜色改成白色会比较好。

默认的颜色下次改成 `#C9AD06`。
