### ISSUE TITLE
侧边栏换个风格的图标？

### ISSUE THREAD

**Issue by BrightVan** [giscafer/leek-fund#65]
主要显示vscode的图标都是线型中空的。目前的图标有点不统一，当然了，只是建议。一般都是从iconfont找图标，搜索趋势，还是有不少类似形状的icon的。比如下面这种？
![image](https://user-images.githubusercontent.com/9381559/91926797-9d231780-ed0a-11ea-8f30-d2a291fafbe8.png)

**Comment by giscafer** [comment]
可以考虑
