### ISSUE TITLE
侧边栏不自动刷新

### ISSUE THREAD

**Issue by shineZz** [giscafer/leek-fund#69]
更新插件后，底部状态栏能自动刷新数据，侧边栏不能像以前一样自动更新数据，只能手动刷新

**Comment by giscafer** [comment]
> 更新插件后，底部状态栏能自动刷新数据，侧边栏不能像以前一样自动更新数据，只能手动刷新
> 
基金还是股票？股票目前有问题是折叠了基金股票不刷新，你展开基金的时候看看是不是正常。

**Comment by shineZz** [comment]
好的，展开之后是可以的

**Comment by giscafer** [comment]
![image](https://user-images.githubusercontent.com/8676711/92266519-29535b80-ef12-11ea-9a09-a441c4c9da9d.png)
