### ISSUE TITLE
侧边栏股票点击打开无效

### ISSUE THREAD

**Issue by niumeng07** [giscafer/leek-fund#74]
## Bug Report

侧边栏股票点击打开无效，重启vscode后正常。
基金点击打开正常。

## Current Behavior?
点击没有反应

## Expected Behavior?
点击打开页面

##  Your Environment [Optional]
Leek-fund版本信息：v1.5.3
Vscode版本信息： 
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

**Comment by giscafer** [comment]
可能是 `Darwin x64 19.6.0` 系统问题呀。我这边没这个没法排查这个问题。是否懂前端调试一下？

**Comment by giscafer** [comment]
无反馈，无重现。关闭
