### ISSUE TITLE
盈亏显示有问题

### ISSUE THREAD

**Issue by VisionBao** [giscafer/leek-fund#78]
## Bug Report
 页面显示盈亏有问题

## Current Behavior?
具体的原因是因为vscode 昨天没有关闭，今天直接用，盈亏就会累加昨天的盈亏。导致今天的盈亏计算错误。

## Expected Behavior?
实际应该只显示今天的盈亏，而和昨天的盈亏不相关。

##  Your Environment [Optional]
VSCode 版本: 1.49.0
macOS 版本 10.15.6

**Comment by giscafer** [comment]
是的，重启vscode 的时候才会去更新本金。目前的逻辑。

**Comment by aihanle1314** [comment]
在设置雪球网cookie按照提示操作后，vscode会报  [giscafer.leek-fund]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api giscafer.leek-fund。
有人遇到过这个问题吗，谢谢
