### ISSUE TITLE
请问，项目的代码跟另一个项目的代码几乎一样有解释吗？

### ISSUE THREAD

**Issue by ToPeas** [giscafer/leek-fund#8]
我今天早上看到另一个仓库的stock-watch。
https://github.com/TDGarden/stock-watch
你们的代码很类似，别人是2年前的项目了，请问是借鉴吗？

**Comment by giscafer** [comment]
@ToPeas 


灵感来自 [stock-watch](https://github.com/TDGarden/stock-watch)插件，不过此只有股票，没有基金，个人只养鸡不玩股票，所以借鉴了代码并按个人的想法开发基金模块和菜单面板等功能，功能主要有：

- 基金涨跌查看，可自定义配置基金代码，支持查看基金历史净值详情
- 股票涨跌查看，可自定义配置股票代码，支持查看股票实时 K 线图
- 左侧菜单面板
- 底部状态 bar
- 支持 GUI 操作新增&删除基金

**Comment by ToPeas** [comment]
readme不展示下？
