### ISSUE TITLE
资金流向打不开

### ISSUE THREAD

**Issue by happyday517** [giscafer/leek-fund#80]
## Bug Report

资金流向打不开
## Current Behavior?

点击后，标签页里空白，什么都不显示

##  Your Environment [Optional]

MacOS 10.13.6，插件版本：v1.5.8
VSCode：
版本: 1.49.0
提交: e790b931385d72cf5669fcefc51cdf65990efa5d
日期: 2020-09-10T17:39:53.251Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

**Comment by giscafer** [comment]
fixed at version `v1.5.9`
