### ISSUE TITLE
股票基金高亮

### ISSUE THREAD

**Issue by ladychili** [giscafer/leek-fund#82]
1.  希望可以高亮（重点关注）某只股票、基金，
2. 希望可以设定高亮产品总是排在前面（优先级高过一般排序）

**Comment by giscafer** [comment]
感兴趣的可以PR，这个本人不开发。觉得没必要。

**Comment by giscafer** [comment]
详细看API，并不支持颜色高亮。html模板的方式可以支持高亮，但是实现右键菜单有弊端，所以权衡不支持次功能了。
