### ISSUE TITLE
恒生指数不支持

### ISSUE THREAD

**Issue by whichow** [giscafer/leek-fund#88]
## Bug Report
![image](https://user-images.githubusercontent.com/17426175/95806053-61cc2d80-0d39-11eb-8954-23aa9a6fc9d8.png)

**Comment by giscafer** [comment]
新浪股票接口不支持

**Comment by iporer** [comment]
恒生指数通过GUI添加的代码和接口获取数据的代码大小写不一致。
手动修改配置文件改喂hkHSI就可以了
