### ISSUE TITLE
股价提醒设置功能体验上还需要优化：

### ISSUE THREAD

**Issue by giscafer** [giscafer/leek-fund#92]
1、不看配置不知道设置了哪些股票提醒；
2、设置了股票提醒后没有取消提醒的功能；
3、输入价格和涨跌比的体验不足。
4、提示信息会一直在提示，这个频率和接口请求频率一样，感觉有点频繁，需要考虑如何提升体验。

解决方案
- 可以和持仓金额类似的webview页面，这样就解决了以上3个问题，价格和涨跌分开是两个输入框。
- 或者是更好的交互方式

**Comment by zqjimlove** [comment]
一开始没考虑太细，因为有需要用到这个功能。所以比较粗暴的实现了。后续参考一下同花顺之类的APP做一次优化。

**Comment by giscafer** [comment]
@zqjimlove 感谢PR，有空考虑优化是吗，那我指派给你了。有空再搞就行，不急

**Comment by zqjimlove** [comment]
> @zqjimlove 感谢PR，有空考虑优化是吗，那我指派给你了。有空再搞就行，不急

没问题的。后面我优化一下

**Comment by giscafer** [comment]
提示：代码重构了，改代码记得更新
