### ISSUE TITLE
收益率小数位数异常导致设置持仓信息界面整体变形

### ISSUE THREAD

**Issue by haogg1996** [giscafer/leek-fund#96]
![image](https://user-images.githubusercontent.com/13046221/97840729-80fa2180-1d1f-11eb-9e97-8e9059c98855.png)

**Comment by giscafer** [comment]
忘记保留小数位了吗？这两个长的有小数点吗？
![image](https://user-images.githubusercontent.com/8676711/97841497-e7337400-1d20-11eb-9c1c-e209fb4d0a0b.png)

**Comment by haogg1996** [comment]
是的，是小数位过长




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nickbing Lao"<notifications@github.com&gt;; 
发送时间: 2020年11月2日(星期一) 下午3:35
收件人: "giscafer/leek-fund"<leek-fund@noreply.github.com&gt;; 
抄送: "jianghao"<1210060701@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [giscafer/leek-fund] 收益率小数位数异常导致设置持仓信息界面整体变形 (#96)





 
忘记保留小数位了吗？这两个长的有小数点吗？

**Comment by giscafer** [comment]
@haogg1996 需要提供一下两个数值，富国精准医疗混合 的持仓成本价和持仓金额。我这边才好复现，因为目前代码是有做小数位控制的
![Uploading image.png…]()

**Comment by giscafer** [comment]
fixed at v1.6.8 version
